version: "3"

services:
  postgres:
    image: postgres:10.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: amedium
      POSTGRES_PASSWORD: amedium2019
      POSTGRES_DB: amediumdb
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: ~
